#!/bin/bash

./gradlew publishAllPublicationsToMavenRepository -x publishKotlinMultiplatformPublicationToMavenRepository -x publishMetadataPublicationToMavenRepository -x publishJvmPublicationToMavenRepository

