#!/bin/bash

./gradlew publishAllPublicationsToMavenRepository -x publishKotlinMultiplatformPublicationToMavenRepository -x publishJvmPublicationToMavenRepository -x publishAndroidDebugPublicationToMavenRepositor -x publishAndroidReleasePublicationToMavenRepository

