
name: Build project and push to maven snapshot
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
#on:
#  push:
#    branches:
#      - main

env:
  CHROME_BIN: "chromium"
  
jobs:
  Build-And-Push:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Android SDK
        uses: amyu/setup-android@v2
      - run:  ./linuxBuild.sh