package com.ionspin.kotlin.crypto.authenticated

import com.ionspin.kotlin.crypto.SRNG

/**
 * Created by Ugljesa Jovanovic
 * ugljesa.jovanovic@ionspin.com
 * on 14-Jun-2020
 */
internal class Aes256GcmStatelessPure : Aes256GcmStateless {
    /**
     * Nonce autogenerated
     */
    override fun encrypt(message: UByteArray, additionalData: UByteArray, rawData : UByteArray, key: Aes256GcmKey) : Aes256GcmEncryptionResult {

        TODO()

    }

    override fun decrypt(encryptedData: UByteArray, nonce: UByteArray, key: Aes256GcmKey): UByteArray {
        TODO("not implemented yet")
    }

}
