package com.ionspin.kotlin.crypto.authenticated

/**
 * Created by Ugljesa Jovanovic
 * ugljesa.jovanovic@ionspin.com
 * on 14-Jun-2020
 */
class Aes256GcmStatelessPure : Aes256GcmStateless {
    /**
     * Nonce autogenerated
     */
    override fun encrypt(message: UByteArray, additionalData: UByteArray, rawData : UByteArray, key:) : Aes256GcmEncryptionResult {

        TODO()

    }

}